github-profile: https://github.com/dunneev
title: 
theme: jekyll-theme-cayman
colors:
  - dark-primary: \#222831
  - dark-secondary: \#393e46
  - clickable: \#cc773f
  - accent: \#42cad1
excerpt_separator: <!--end-excerpt-->



# Any plugins within jekyll_plugin group from Gemfile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

# Exclude these files from the build process results.
# Prevents them from showing up in the master branch which 
# is the live site.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile

# show_downloads: true